# Generated by Django 4.1.3 on 2022-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Introducao', models.CharField(max_length=100)),
                ('Ingredientes', models.CharField(max_length=200)),
                ('Instrucoes', models.CharField(max_length=600)),
                ('Notas', models.CharField(max_length=300)),
            ],
        ),
    ]
