# Generated by Django 4.1.3 on 2022-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='Ingredientes',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='Instrucoes',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='Introducao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='Notas',
            field=models.TextField(max_length=300),
        ),
    ]
