# Generated by Django 4.1.3 on 2022-12-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_alter_receitas_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='Introducao',
        ),
    ]
