# Generated by Django 4.1.3 on 2022-12-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='Nome_Receita',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='Notas',
            field=models.TextField(max_length=225),
        ),
    ]
